reference_product:
  name: evk_8ulp
  device: evk_8ulp
  soc_type: IMX8ULP
  AndroidProducts_root: device/nxp/imx8ulp

target_product:
  name: evk_93
  device: evk_93
  soc_type: IMX93
  repo_path: device/nxp
  AndroidProducts_root: device/nxp/imx9
  manufacturer: nxp

modules:
  app: y
  audio: y
  bluetooth: y
  camera: y
  common_config: y
  display: y
  ethernet: y
  gpu: n
  infrastructure: y
  input: y
  isp: n
  kernel_bootimg: y
  memory: y
  miscellaneous: y
  multimedia_codec: y
  neural_network: y
  power: y
  profile: y
  security: y
  sensor: y
  sepolicy: y
  storage: y
  treble: y
  usb: y
  wifi: y
